version: '3'
services:
        postgis:
                image: mdillon/postgis:10-alpine
                ports: 
                        - 5432:5432
                environment:
                        POSTGRES_DB: geoslurp
                        POSTGRES_USER: geoslurp
                        POSTGRES_PASSWORD: Swapforyour0wn
                restart: always
